import type { McpServer } from "../data/servers";

/**
 * Parsing and validation for the inspector's deep-link query parameters
 * (`?server=&tab=&name=`).
 *
 * Split out of `Inspector.tsx` so the parsing logic is plain data in, plain
 * data out — testable with `node --test`, no DOM or Preact involved — and so
 * the `Tab` union has one definition instead of two that could drift apart.
 *
 * The URL is public and shareable: anyone can hand-edit it, bookmark a stale
 * version, or have it generated by a page nobody reviewed. Every parameter
 * here is therefore validated on the way in, and anything that doesn't
 * validate is dropped silently rather than surfaced as an error — the caller
 * falls back to the inspector's normal defaults.
 *
 * NEVER add a parameter for a credential here. This module is the single
 * place that decides what the URL is allowed to carry, and the visitor's
 * GitLab token must never be one of those things — see the "THE RULE THAT
 * CANNOT BE BROKEN" comment at the top of `Inspector.tsx`.
 */

/** The three things a server can offer through the inspector. */
export type Tab = "tools" | "prompts" | "resources";

/** All three tabs, in the order they're shown. */
export const TABS: Tab[] = ["tools", "prompts", "resources"];

/**
 * Deep-link state read from the URL's query string.
 *
 * Every field is independently optional: a request can get the server right
 * and the tab wrong, and only the tab should fall back to its default.
 */
export type DeepLink = {
  /** A server id from `servers`, or `undefined` if absent or unrecognised. */
  serverId: string | undefined;
  /** One of `TABS`, or `undefined` if absent or not one of the three. */
  tab: Tab | undefined;
  /**
   * The tool/prompt/resource name to preselect, or `undefined` if absent.
   *
   * Deliberately NOT checked against a catalog here: `tools/list` and its
   * siblings are only fetched after the visitor loads them, so at parse time
   * there is no list yet to validate `name` against. The caller re-checks it
   * once the matching catalog actually loads.
   */
  name: string | undefined;
};

/** `true` if `value` is one of `TABS`. */
function isTab(value: string): value is Tab {
  return (TABS as string[]).includes(value);
}

/**
 * Reads and validates the inspector's deep-link query parameters.
 *
 * `server` is checked against the real server list; `tab` against the fixed
 * set of three; `name` is returned trimmed and as-is, since it can only be
 * validated once its target catalog has loaded.
 *
 * @param search `location.search`, with or without the leading `?`.
 * @param servers The server list, to validate `server` against.
 * @returns The validated pieces; an unset field means "use the default".
 */
export function parseDeepLink(search: string, servers: McpServer[]): DeepLink {
  const params = new URLSearchParams(search);

  const server = params.get("server");
  const serverId =
    server && servers.some((candidate) => candidate.id === server)
      ? server
      : undefined;

  const tab = params.get("tab");
  const validTab = tab && isTab(tab) ? tab : undefined;

  const name = params.get("name")?.trim();

  return { serverId, tab: validTab, name: name || undefined };
}
