import type { JsonSchema } from "./tool-schema";

/**
 * Reading the protocol's other two catalogs: `prompts/list` and
 * `resources/list`.
 *
 * The inspector only listed them: you could see there were 37 prompts, but not
 * which arguments each one asked for nor what it returned. Here they are
 * normalized so they can be rendered and, above all, used.
 *
 * Prompts declare their arguments as a `{name, description, required}` array,
 * not as a JSON Schema. `promptSchema` translates them into a schema so the
 * form is generated by the same code as the tools' one.
 */

/** One prompt argument, exactly as `prompts/list` declares it. */
export type PromptArgument = {
  name: string;
  description?: string;
  required?: boolean;
};

/** One prompt from the catalog. */
export type McpPrompt = {
  name: string;
  title?: string;
  description?: string;
  arguments: PromptArgument[];
};

/** One resource from the catalog. */
export type McpResource = {
  uri: string;
  name?: string;
  title?: string;
  description?: string;
  mimeType?: string;
};

/**
 * One resource template: a URI with `{placeholders}` rather than a fixed
 * address. gitlab publishes 37 (`gitlab://group/{group_id}`, …) next to its 8
 * fixed resources, so the templates, not the resources, are most of what it
 * actually exposes.
 */
export type McpResourceTemplate = {
  uriTemplate: string;
  name?: string;
  title?: string;
  description?: string;
  mimeType?: string;
};

/**
 * What an `initialize` result says about the server, flattened for display.
 *
 * `instructions` is the one field a model is meant to read: the server's
 * usage guide, sent once at the start of a session (1139 characters for
 * libgen, 3386 for gitlab). `capabilities` is kept as the list of names the
 * server declared, since that list — not the tabs this page happens to show —
 * is what decides which methods it will answer.
 */
export type ServerDoc = {
  protocolVersion?: string;
  name?: string;
  title?: string;
  version?: string;
  description?: string;
  websiteUrl?: string;
  instructions?: string;
  capabilities: string[];
};

/** The value when it is a string; otherwise the fallback. */
function str(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

/** `true` when the value is a plain object (not null, not an array). */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** The array hanging off `result.<key>`, or empty. */
function listOf(body: unknown, key: string): Record<string, unknown>[] {
  if (!isRecord(body)) return [];
  const result = body.result;
  if (!isRecord(result)) return [];
  const items = result[key];
  return Array.isArray(items) ? items.filter((x) => isRecord(x)) : [];
}

/**
 * Normalizes a `prompts/list` response.
 *
 * @param body The response's JSON-RPC body.
 * @returns The prompts, with their arguments already normalized.
 */
export function promptsFrom(body: unknown): McpPrompt[] {
  return listOf(body, "prompts").map((entry) => ({
    name: str(entry.name),
    title: typeof entry.title === "string" ? entry.title : undefined,
    description:
      typeof entry.description === "string" ? entry.description : undefined,
    arguments: Array.isArray(entry.arguments)
      ? entry.arguments
          .filter((a) => isRecord(a))
          .map((a) => ({
            name: str(a.name),
            description:
              typeof a.description === "string" ? a.description : undefined,
            required: a.required === true,
          }))
      : [],
  }));
}

/**
 * Normalizes a `resources/list` response.
 *
 * @param body The response's JSON-RPC body.
 * @returns The resources the server declares.
 */
export function resourcesFrom(body: unknown): McpResource[] {
  return listOf(body, "resources").map((entry) => ({
    uri: str(entry.uri),
    name: typeof entry.name === "string" ? entry.name : undefined,
    title: typeof entry.title === "string" ? entry.title : undefined,
    description:
      typeof entry.description === "string" ? entry.description : undefined,
    mimeType: typeof entry.mimeType === "string" ? entry.mimeType : undefined,
  }));
}

/**
 * Translates a prompt's arguments into a JSON Schema.
 *
 * Prompts declare no schema — only a name, a description and whether it is
 * required — but the form already knows how to render a schema. Translating
 * them here avoids a second form generator that would drift from the first.
 *
 * Every prompt argument is a string by the protocol's definition.
 *
 * @param args The arguments the prompt declares.
 * @returns An equivalent schema.
 */
export function promptSchema(args: PromptArgument[]): JsonSchema {
  return {
    type: "object",
    properties: Object.fromEntries(
      args.map((a) => [a.name, { type: "string", description: a.description }]),
    ),
    required: args.filter((a) => a.required).map((a) => a.name),
  };
}

/**
 * Normalizes a `resources/templates/list` response.
 *
 * @param body The response's JSON-RPC body.
 * @returns The templates; entries without a `uriTemplate` are kept with an
 *   empty one rather than dropped, so a malformed server is visible as such.
 */
export function templatesFrom(body: unknown): McpResourceTemplate[] {
  return listOf(body, "resourceTemplates").map((entry) => ({
    uriTemplate: str(entry.uriTemplate),
    name: typeof entry.name === "string" ? entry.name : undefined,
    title: typeof entry.title === "string" ? entry.title : undefined,
    description:
      typeof entry.description === "string" ? entry.description : undefined,
    mimeType: typeof entry.mimeType === "string" ? entry.mimeType : undefined,
  }));
}

/** An optional string field, or undefined. */
function opt(record: Record<string, unknown>, key: string): string | undefined {
  const value = record[key];
  return typeof value === "string" && value !== "" ? value : undefined;
}

/**
 * Reads an `initialize` result into a {@link ServerDoc}.
 *
 * @param body The response's JSON-RPC body.
 * @returns The document, or `undefined` when the body carries no result
 *   (an error, or a 401 before a credential was given).
 */
export function serverDocFrom(body: unknown): ServerDoc | undefined {
  if (!isRecord(body) || !isRecord(body.result)) return undefined;
  const result = body.result;
  const info = isRecord(result.serverInfo) ? result.serverInfo : {};
  const caps = isRecord(result.capabilities) ? result.capabilities : {};
  return {
    protocolVersion: opt(result, "protocolVersion"),
    name: opt(info, "name"),
    title: opt(info, "title"),
    version: opt(info, "version"),
    description: opt(info, "description"),
    websiteUrl: opt(info, "websiteUrl"),
    instructions: opt(result, "instructions"),
    capabilities: Object.keys(caps).toSorted((x, y) => x.localeCompare(y)),
  };
}

/**
 * `true` when a list call was answered "method not found" (-32601).
 *
 * That is the server saying it does not implement the category at all, which
 * is different from an empty list: libgen declares no `resources` capability
 * and answers `resources/list` with -32601. The inspector used to show that
 * as a raw error, as if something had broken; it now says what it means.
 *
 * @param body The response's JSON-RPC body.
 * @returns Whether the method is not implemented.
 */
export function isMethodNotFound(body: unknown): boolean {
  if (!isRecord(body) || !isRecord(body.error)) return false;
  // A JSON-RPC spec code, not a quantity.
  // eslint-disable-next-line unicorn/numeric-separators-style
  return body.error.code === -32601;
}
