import type { JsonSchema } from "./tool-schema";

/**
 * Reading the protocol's other two catalogs: `prompts/list` and
 * `resources/list`.
 *
 * The inspector only listed them: you could see there were 37 prompts, but not
 * which arguments each one asked for nor what it returned. Here they are
 * normalized so they can be rendered and, above all, used.
 *
 * Prompts declare their arguments as a `{name, description, required}` array,
 * not as a JSON Schema. `promptSchema` translates them into a schema so the
 * form is generated by the same code as the tools' one.
 */

/** One prompt argument, exactly as `prompts/list` declares it. */
export type PromptArgument = {
  name: string;
  description?: string;
  required?: boolean;
};

/** One prompt from the catalog. */
export type McpPrompt = {
  name: string;
  title?: string;
  description?: string;
  arguments: PromptArgument[];
};

/** One resource from the catalog. */
export type McpResource = {
  uri: string;
  name?: string;
  title?: string;
  description?: string;
  mimeType?: string;
};

/** The value when it is a string; otherwise the fallback. */
function str(value: unknown, fallback = ""): string {
  return typeof value === "string" ? value : fallback;
}

/** `true` when the value is a plain object (not null, not an array). */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/** The array hanging off `result.<key>`, or empty. */
function listOf(body: unknown, key: string): Record<string, unknown>[] {
  if (!isRecord(body)) return [];
  const result = body.result;
  if (!isRecord(result)) return [];
  const items = result[key];
  return Array.isArray(items) ? items.filter((x) => isRecord(x)) : [];
}

/**
 * Normalizes a `prompts/list` response.
 *
 * @param body The response's JSON-RPC body.
 * @returns The prompts, with their arguments already normalized.
 */
export function promptsFrom(body: unknown): McpPrompt[] {
  return listOf(body, "prompts").map((entry) => ({
    name: str(entry.name),
    title: typeof entry.title === "string" ? entry.title : undefined,
    description:
      typeof entry.description === "string" ? entry.description : undefined,
    arguments: Array.isArray(entry.arguments)
      ? entry.arguments
          .filter((a) => isRecord(a))
          .map((a) => ({
            name: str(a.name),
            description:
              typeof a.description === "string" ? a.description : undefined,
            required: a.required === true,
          }))
      : [],
  }));
}

/**
 * Normalizes a `resources/list` response.
 *
 * @param body The response's JSON-RPC body.
 * @returns The resources the server declares.
 */
export function resourcesFrom(body: unknown): McpResource[] {
  return listOf(body, "resources").map((entry) => ({
    uri: str(entry.uri),
    name: typeof entry.name === "string" ? entry.name : undefined,
    title: typeof entry.title === "string" ? entry.title : undefined,
    description:
      typeof entry.description === "string" ? entry.description : undefined,
    mimeType: typeof entry.mimeType === "string" ? entry.mimeType : undefined,
  }));
}

/**
 * Translates a prompt's arguments into a JSON Schema.
 *
 * Prompts declare no schema — only a name, a description and whether it is
 * required — but the form already knows how to render a schema. Translating
 * them here avoids a second form generator that would drift from the first.
 *
 * Every prompt argument is a string by the protocol's definition.
 *
 * @param args The arguments the prompt declares.
 * @returns An equivalent schema.
 */
export function promptSchema(args: PromptArgument[]): JsonSchema {
  return {
    type: "object",
    properties: Object.fromEntries(
      args.map((a) => [a.name, { type: "string", description: a.description }]),
    ),
    required: args.filter((a) => a.required).map((a) => a.name),
  };
}
