/**
 * The Nginx configuration this build can generate, staged for the deploy.
 *
 * ── Why generate it ───────────────────────────────────────────────────────
 * The vhost carried one hand-written `location =` per markdown twin — sixty
 * of them, added by hand every time a page shipped — plus two nested
 * `location ~ \.md$` blocks for the action pages, which existed only because
 * `^~` beats a regex and a top-level regex would never have seen them. All of
 * it is derivable from one question the build can answer for itself: which
 * `<page>/index.md` files did it write? A rule computed from the build cannot
 * drift from the pages it serves, and the vhost stops being a list to
 * maintain.
 *
 * ── Where it goes, and why not into dist/ ─────────────────────────────────
 * Into a staging directory OUTSIDE the repository and OUTSIDE the served
 * tree. The two security-header snippets are written into `dist/` today,
 * where the only thing between a configuration file and the public is the
 * vhost's allowlist continuing to be correct; and a file written into the
 * repository working tree would be rewritten by a `git checkout`, with the
 * next reload — from certbot, from a cron, from anyone — applying it. jmrp.io
 * hit exactly that and moved its own generated config out (32f010c).
 *
 * The staging directory is on the same filesystem as /etc/nginx so the
 * delivery in `deploy-live-mcp.mjs` is a real rename(2), and the file mode is
 * set explicitly: a snippet the nginx workers cannot read produces a 520 on
 * the NEXT reload, long after the build that caused it, and `nginx -t` does
 * not catch it because the master runs as root.
 */
import fs from "node:fs";
import path from "node:path";

import type { AstroIntegrationLogger } from "astro";

/**
 * Where the generated snippets are staged.
 *
 * Overridable so a scratch build (`astro build --outDir builds/scratch`) can
 * be exercised without touching what the next deploy would deliver.
 */
export const STAGING_DIR =
  process.env.MCP_NGINX_STAGING ?? "/var/lib/mcp.jmrp.io/nginx-staged";

/** Prefix on every generated file, so a stray name cannot collide with jmrp.io's. */
const PREFIX = "mcp_";

/** An escaped double quote, as Nginx needs it inside a quoted map value. */
const Q = String.raw`\"`;

/** `/servers/<id>/actions/<domain>/`, either language. */
const ACTIONS_PAGE = /^\/(?:es\/)?servers\/[^/]+\/actions\/[^/]+\/$/;

/**
 * Header every generated snippet carries.
 *
 * `nginx -T` prints the running configuration; a stamp is what lets someone
 * reading it tell a file this build delivered from one seeded by hand.
 *
 * @param name The snippet's file name.
 * @returns The comment block to prepend.
 */
function stamp(name: string): string {
  return (
    `# ${name} — GENERATED by mcp.jmrp.io's build. Do not edit by hand.\n` +
    `# Build-Stamp: ${new Date().toISOString()}\n` +
    `# Source: src/integrations/post-build/nginx-snippets.ts\n\n`
  );
}

/**
 * Writes one snippet into the staging directory.
 *
 * Written to a temporary name in the same directory and renamed over the
 * target, so a reader never sees a half-written file, and chmod'ed
 * explicitly rather than left to the umask.
 *
 * @param name File name, prefix included.
 * @param body The configuration.
 */
function writeSnippet(name: string, body: string): void {
  const target = path.join(STAGING_DIR, name);
  const temporary = `${target}.tmp-${process.pid}`;
  fs.writeFileSync(temporary, stamp(name) + body, { mode: 0o644 });
  // Explicit, and not left to the umask: the nginx workers run unprivileged
  // and cannot read a 0600 snippet. That fails on the NEXT reload rather than
  // at build time, and `nginx -t` passes because the master is root.
  // eslint-disable-next-line sonarjs/file-permissions -- 0644 is the fix, see above
  fs.chmodSync(temporary, 0o644);
  fs.renameSync(temporary, target);
}

/**
 * Every markdown twin the build wrote, as its page path.
 *
 * A twin is always `<page>/index.md`, so the page is the containing directory
 * with a trailing slash. `index.md.br` and `index.md.gz` come from the
 * compression step and must not match, which is why the name test is exact.
 *
 * @param dir Directory to walk.
 * @param base URL path accumulated so far.
 * @returns Page paths with a leading and trailing slash.
 */
function twinPages(dir: string, base = ""): string[] {
  const pages: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      pages.push(
        ...twinPages(path.join(dir, entry.name), `${base}/${entry.name}`),
      );
    } else if (entry.isFile() && entry.name === "index.md") {
      pages.push(`${base}/`);
    }
  }
  return pages.sort((a, b) => a.localeCompare(b));
}

/**
 * Generates the snippets and stages them.
 *
 * Never fatal. Off the production host — CI, a fresh clone, a scratch build —
 * the staging directory does not exist and cannot be created, and that is the
 * normal case there: the build's job is the site, and the configuration is
 * delivered by the deploy. It warns rather than failing, the same way the
 * deploy warns when its own path is unset.
 *
 * @param distDir The build output directory.
 * @param logger Astro's logger.
 */
export function stageNginxSnippets(
  distDir: string,
  logger: AstroIntegrationLogger,
): void {
  const pages = twinPages(distDir);
  if (pages.length === 0) {
    logger.warn(
      "  ⚠ no markdown twins found: the Nginx snippets are not staged",
    );
    return;
  }

  try {
    fs.mkdirSync(STAGING_DIR, { recursive: true, mode: 0o755 });
  } catch {
    logger.info(
      `  ℹ ${STAGING_DIR} is not writable: skipping the Nginx snippets ` +
        "(expected off the production host)",
    );
    return;
  }

  // One exact location per twin. `location =` outranks every prefix and regex
  // match, so these work wherever they are included and the nested
  // `location ~ \.md$` blocks the actions prefixes needed can go.
  //
  // The security headers are included HERE and not inherited. A location that
  // declares any `add_header` of its own stops inheriting the server's set —
  // the same nginx rule the vhost relies on to keep COEP and CORP off the MCP
  // endpoints — and this block declares `add_header Link`. Without the
  // include the twins were the one class of location on the site serving zero
  // security headers from the origin, `X-Content-Type-Options` among them,
  // which is the one that matters on `text/markdown`. The assets variant is
  // the right snippet: it carries no nonce-bearing CSP, which markdown has no
  // use for.
  const locations = pages
    .map(
      (page) =>
        `location = ${page}index.md { default_type "text/markdown; charset=utf-8"; ` +
        `include /etc/nginx/snippets/security_headers_assets_mcp.conf; ` +
        `add_header Link $mcp_md_link_header always; try_files ${page}index.md =404; }`,
    )
    .join("\n");

  // The typed link an HTML response adds to its own `Link` header, so the
  // twin can be discovered from a HEAD request without parsing the body. The
  // head tag `Base.astro` emits is the primary channel; this is the second
  // one, for the same audience as the `describedby` link already served.
  const alternates = [
    "map $uri $mcp_md_alternate {",
    '    default "";',
    // TWO keys per page. The map is read at header time, by which point
    // `$uri` is the file `try_files` resolved to — `/license/index.html`, not
    // `/license/` — so keying only on the pretty path matched nothing and the
    // header came out without the link. Both forms are emitted rather than
    // switching to `$request_uri`, which carries the query string and would
    // stop matching the moment a URL had one.
    ...pages.flatMap((page) => {
      const value =
        `", <https://mcp.jmrp.io${page}index.md>; rel=${Q}alternate${Q}; ` +
        `type=${Q}text/markdown${Q}";`;
      return [`    ${page} ${value}`, `    ${page}index.html ${value}`];
    }),
    "}",
  ].join("\n");

  // Every other route on the site answers 308 when its trailing slash is
  // dropped, from a hand-written `location =` in the vhost. The action pages
  // never got one: there are fifty-six of them, which is exactly why nobody
  // wrote them by hand, and their prefix block does
  // `try_files ${uri}index.html =404`, so a path ending in `/issue` resolved
  // to a file named `issue` with `index.html` glued to it, and missed.
  // A regex `location` could not rescue it either, because `^~` on the prefix
  // block outranks every regex. That matters more here than it looks: these
  // are the deep pages an assistant cites, and assistants routinely emit URLs
  // without the trailing slash, so each such citation was a dead link.
  //
  // Scoped to the action pages ON PURPOSE. Emitting a redirect for every page
  // would collide with the vhost's hand-written ones, and a duplicate
  // `location =` is a configuration error — `nginx -t` would fail the deploy.
  const redirects = pages
    .filter((page) => ACTIONS_PAGE.test(page))
    .map((page) => `location = ${page.slice(0, -1)} { return 308 ${page}; }`)
    .join("\n");

  writeSnippet(`${PREFIX}md_twin_locations.conf`, `${locations}\n`);
  writeSnippet(`${PREFIX}md_twin_alternates.conf`, `${alternates}\n`);
  writeSnippet(`${PREFIX}actions_slash_redirects.conf`, `${redirects}\n`);
  logger.info(
    `  ✓ Staged ${PREFIX}md_twin_locations.conf and ${PREFIX}md_twin_alternates.conf ` +
      `(${pages.length} twins) in ${STAGING_DIR}`,
  );
  logger.info(
    `  ✓ Staged ${PREFIX}actions_slash_redirects.conf ` +
      `(${redirects ? redirects.split("\n").length : 0} action pages)`,
  );
}
